"""empty message

Revision ID: 105078b712ad
Revises: b5d424e0067d
Create Date: 2022-08-30 23:38:23.004322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105078b712ad'
down_revision = 'b5d424e0067d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
